import { z } from "zod";

const nullableString = z.string().trim().nullable();
const optionalNullableString = nullableString.optional();
const optionalBoolean = z.boolean().optional();
const optionalDateString = z.string().datetime({ offset: true }).or(z.string().date()).nullable().optional();

export const prepareJoiningStatusSchema = z.enum([
  "PENDING",
  "DOCUMENTS",
  "MEDICAL",
  "TRAINING",
  "TRAVEL",
  "READY",
  "DISPATCHED",
  "CANCELLED",
]);

export const prepareJoiningUpdateSchema = z.object({
  status: prepareJoiningStatusSchema.optional(),
  passportValid: optionalBoolean,
  seamanBookValid: optionalBoolean,
  certificatesValid: optionalBoolean,
  medicalValid: optionalBoolean,
  visaValid: optionalBoolean,
  orientationCompleted: optionalBoolean,
  ticketBooked: optionalBoolean,
  hotelBooked: optionalBoolean,
  transportArranged: optionalBoolean,
  medicalCheckDate: optionalDateString,
  medicalExpiry: optionalDateString,
  orientationDate: optionalDateString,
  departureDate: optionalDateString,
  departurePort: optionalNullableString,
  arrivalPort: optionalNullableString,
  flightNumber: optionalNullableString,
  hotelName: optionalNullableString,
  remarks: optionalNullableString,
  vesselId: optionalNullableString,
  principalId: optionalNullableString,
  mcuScheduled: optionalBoolean,
  mcuScheduledDate: optionalDateString,
  mcuCompleted: optionalBoolean,
  mcuCompletedDate: optionalDateString,
  mcuDoctorName: optionalNullableString,
  mcuClinicName: optionalNullableString,
  mcuResult: optionalNullableString,
  mcuRestrictions: optionalNullableString,
  mcuRemarks: optionalNullableString,
  vaccineYellowFever: optionalBoolean,
  vaccineHepatitisA: optionalBoolean,
  vaccineHepatitisB: optionalBoolean,
  vaccineTyphoid: optionalBoolean,
  vaccineOther: optionalNullableString,
  vaccineExpiryDate: optionalDateString,
  safetyLifeJacket: optionalBoolean,
  safetyHelmet: optionalBoolean,
  safetyShoes: optionalBoolean,
  safetyGloves: optionalBoolean,
  safetyHarnessVest: optionalBoolean,
  workUniform: optionalBoolean,
  workIDCard: optionalBoolean,
  workAccessCard: optionalBoolean,
  workStationery: optionalBoolean,
  workToolsProvided: optionalBoolean,
  personalPassport: optionalBoolean,
  personalVisa: optionalBoolean,
  personalTickets: optionalBoolean,
  personalVaccineCard: optionalBoolean,
  personalMedicalCert: optionalBoolean,
  vesselStatroomAssigned: optionalBoolean,
  vesselStatroomNumber: optionalNullableString,
  vesselContractSigned: optionalBoolean,
  vesselBriefingScheduled: optionalBoolean,
  vesselBriefingDate: optionalDateString,
  vesselOrientationDone: optionalBoolean,
  vesselEmergencyDrill: optionalBoolean,
  preDepartureDocCheck: optionalBoolean,
  preDepartureEquipCheck: optionalBoolean,
  preDepartureMedicalOK: optionalBoolean,
  preDepartureEmergency: optionalBoolean,
  preDepartureSalaryOK: optionalBoolean,
  preDeparturePerDiem: optionalBoolean,
  preDepartureFinalCheck: optionalBoolean,
  preDepartureApprovedBy: optionalNullableString,
  preDepartureApprovedAt: optionalDateString,
  preDepartureChecklistBy: optionalNullableString,
}).strict();

export const prepareJoiningCreateSchema = z.object({
  crewId: z.string().min(1, "Crew ID is required"),
  vesselId: optionalNullableString,
  principalId: optionalNullableString,
  status: prepareJoiningStatusSchema.optional(),
  passportValid: z.boolean().optional().default(false),
  seamanBookValid: z.boolean().optional().default(false),
  certificatesValid: z.boolean().optional().default(false),
  medicalValid: z.boolean().optional().default(false),
  visaValid: z.boolean().optional().default(false),
  orientationCompleted: z.boolean().optional().default(false),
  ticketBooked: z.boolean().optional().default(false),
  hotelBooked: z.boolean().optional().default(false),
  transportArranged: z.boolean().optional().default(false),
  medicalCheckDate: optionalDateString,
  medicalExpiry: optionalDateString,
  orientationDate: optionalDateString,
  departureDate: optionalDateString,
  departurePort: optionalNullableString,
  arrivalPort: optionalNullableString,
  flightNumber: optionalNullableString,
  hotelName: optionalNullableString,
  remarks: optionalNullableString,
}).strict();

export type PrepareJoiningCreateInput = z.infer<typeof prepareJoiningCreateSchema>;
export type PrepareJoiningUpdateInput = z.infer<typeof prepareJoiningUpdateSchema>;

