// PM2 ecosystem configuration for HIMS App production deployment
module.exports = {
  apps: [
    {
      name: 'hims-app',
      cwd: '/home/hanmarine/hims-app',
      script: 'scripts/start-standalone.cjs',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        UPLOAD_BASE_DIR: '/home/hanmarine/seafarers_files',
        HIMS_SUPPLEMENTAL_ROLE_MAP: '{"dino@hanmarine.co":["QMR"]}',
        HIMS_ADMIN_MAINTENANCE_ACCESS_MAP: '{"arief@hanmarine.co":["USER_MANAGEMENT","SYSTEM_HEALTH","AUDIT_LOGS"]}',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        UPLOAD_BASE_DIR: '/home/hanmarine/seafarers_files',
        HIMS_SUPPLEMENTAL_ROLE_MAP: '{"dino@hanmarine.co":["QMR"]}',
        HIMS_ADMIN_MAINTENANCE_ACCESS_MAP: '{"arief@hanmarine.co":["USER_MANAGEMENT","SYSTEM_HEALTH","AUDIT_LOGS"]}',
      },
      watch: false,
      max_memory_restart: '512M',
      error_file: '/home/hanmarine/hims-app/logs/err.log',
      out_file: '/home/hanmarine/hims-app/logs/out.log',
    },
    {
      name: 'hims-escalation-job',
      cwd: '/home/hanmarine/hims-app',
      script: 'scripts/run-escalation-notify.cjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: false,
      cron_restart: '0 7 * * *',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        TZ: 'Asia/Jakarta',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        TZ: 'Asia/Jakarta',
      },
      watch: false,
      max_memory_restart: '256M',
      error_file: '/home/hanmarine/hims-app/logs/escalation-job.err.log',
      out_file: '/home/hanmarine/hims-app/logs/escalation-job.out.log',
    },
    {
      name: 'hims-office-automation-job',
      cwd: '/home/hanmarine/hims-app',
      script: 'scripts/run-office-automation.cjs',
      instances: 1,
      exec_mode: 'fork',
      autorestart: false,
      cron_restart: '30 6 * * *',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        TZ: 'Asia/Jakarta',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        TZ: 'Asia/Jakarta',
      },
      watch: false,
      max_memory_restart: '256M',
      error_file: '/home/hanmarine/hims-app/logs/office-automation-job.err.log',
      out_file: '/home/hanmarine/hims-app/logs/office-automation-job.out.log',
    },
  ],
};
