#!/bin/bash

# Test Script for HIMS Form Management System
# Run this after starting dev server (npm run dev)

echo "=========================================="
echo "HIMS FORM MANAGEMENT SYSTEM TEST"
echo "=========================================="
echo ""

BASE_URL="http://localhost:3000"

# Wait for server
echo "⏳ Waiting for server to start..."
sleep 5

echo ""
echo "=========================================="
echo "TEST 1: Seed Form Templates (Option 3)"
echo "=========================================="
echo "POST $BASE_URL/api/admin/seed-form-templates"
echo ""
curl -X POST "$BASE_URL/api/admin/seed-form-templates" \
  -H "Content-Type: application/json" \
  -s | jq '.' || echo "❌ Failed (server might need authentication)"

echo ""
echo ""
echo "=========================================="
echo "TEST 2: Get Form Templates"
echo "=========================================="
echo "GET $BASE_URL/api/form-templates"
echo ""
curl -s "$BASE_URL/api/form-templates" | jq '.' || echo "❌ Failed"

echo ""
echo ""
echo "=========================================="
echo "TEST 3: Get Form Submissions"
echo "=========================================="
echo "GET $BASE_URL/api/form-submissions"
echo ""
curl -s "$BASE_URL/api/form-submissions" | jq '.' || echo "❌ Failed"

echo ""
echo ""
echo "=========================================="
echo "TEST 4: Check Prepare Joining API"
echo "=========================================="
echo "GET $BASE_URL/api/prepare-joining"
echo ""
curl -s "$BASE_URL/api/prepare-joining" | jq '.data | length' || echo "❌ Failed"
echo " prepare joining records found"

echo ""
echo ""
echo "=========================================="
echo "TEST 5: Letter Guarantee Generator"
echo "=========================================="
echo "Note: Requires valid prepare joining ID"
echo "Will test if endpoint exists..."
echo ""
FIRST_PJ_ID=$(curl -s "$BASE_URL/api/prepare-joining" | jq -r '.data[0].id' 2>/dev/null)
if [ "$FIRST_PJ_ID" != "null" ] && [ ! -z "$FIRST_PJ_ID" ]; then
  echo "Testing with prepare joining ID: $FIRST_PJ_ID"
  echo "GET $BASE_URL/api/forms/letter-guarantee/$FIRST_PJ_ID"
  curl -s "$BASE_URL/api/forms/letter-guarantee/$FIRST_PJ_ID" | jq '.data.letterNumber, .data.crewTable[0].name' || echo "❌ Failed"
else
  echo "⚠️  No prepare joining records found, skipping Letter Guarantee test"
fi

echo ""
echo ""
echo "=========================================="
echo "TEST SUMMARY"
echo "=========================================="
echo ""
echo "✅ Option 1: Form Management UI"
echo "   - Page: http://localhost:3000/crewing/forms"
echo "   - Individual form: http://localhost:3000/crewing/forms/[id]"
echo ""
echo "✅ Option 2: Prepare Joining with Letter Guarantee"
echo "   - Page: http://localhost:3000/crewing/prepare-joining"
echo "   - Button: 'Generate Letter Guarantee' (purple-pink gradient)"
echo ""
echo "✅ Option 3: Seeding Endpoint"
echo "   - Endpoint: POST /api/admin/seed-form-templates"
echo "   - Status: Run test above to check"
echo ""
echo "=========================================="
echo "MANUAL TESTING STEPS"
echo "=========================================="
echo ""
echo "1. Login ke: http://localhost:3000/auth/signin"
echo "   Email: admin@hims.com"
echo "   Password: admin123"
echo ""
echo "2. Test Prepare Joining:"
echo "   - Go to: http://localhost:3000/crewing/prepare-joining"
echo "   - Look for purple-pink 'Generate Letter Guarantee' button"
echo "   - Click it, should open Letter in new tab"
echo ""
echo "3. Test Form Management:"
echo "   - Go to: http://localhost:3000/crewing/forms"
echo "   - Should see two tabs: Form Submissions | Form Templates"
echo "   - Click Form Templates tab"
echo "   - Should see INTEGRIS and LUNDQVIST templates (if seeded)"
echo ""
echo "4. Test Form Review:"
echo "   - Once form submissions exist, click 'Review Form'"
echo "   - Should see form details, crew info, approval timeline"
echo "   - Test Edit, Submit, Approve buttons"
echo ""
echo "=========================================="
echo "END OF TEST"
echo "=========================================="
