'use client';

import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import Link from "next/link";

export default function HGQSManagementGuidelines() {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === "loading") return;
    if (!session) {
      router.push("/auth/signin");
    }
  }, [session, status, router]);

  if (status === "loading") {
    return <div>Loading...</div>;
  }

  if (!session) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100">
      {/* Header */}
      <header className="bg-white backdrop-blur-lg shadow-2xl border-b border-white/20">
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between">
            <div>
              <Link
                href="/quality"
                className="text-blue-600 hover:text-blue-800 font-medium"
              >
                ← Back to Quality Management
              </Link>
              <h1 className="text-3xl font-bold bg-gradient-to-r from-slate-700 to-slate-900 bg-clip-text text-transparent mt-2">
                HGQS Management Guidelines
              </h1>
              <p className="text-lg text-gray-700 mt-1">Doc. No.: HGQS-MG | Rev. No.: 00 | Enf. Date: 2023.07.03</p>
            </div>
            <div className="flex items-center space-x-4">
              <div className="bg-blue-100 text-blue-800 px-3 py-2 rounded-full text-sm font-medium">
                Office Employees
              </div>
              <div className="bg-green-100 text-green-800 px-3 py-2 rounded-full text-sm font-medium">
                Policies & Ethics
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        <div className="bg-white backdrop-blur-md rounded-xl shadow-lg border border-gray-100 p-8">
          <div className="prose prose-slate max-w-none">
            <h2>HGQSMANAGEMENT GUIDELINE FOR OFFICE EMPLOYEES</h2>
            <p>Doc. No.: HGQS - MG<br/>Leg. Date: 2023.07.03<br/>Rev. No.: 00<br/>Enf. Date: 2023.07.03</p>
            <p>Prepared by Reviewed by Approved by<br/>Quality Management Representative<br/>Mr. Afrian Al Hadino Director<br/>Mr. Mochamad Rinaldy Director<br/>Mr. Mochamad Rinaldy<br/>Signature Signature Signature<br/>2023.07.03 2023.07.03 2023.07.03</p>
            <h3>PT.HANMARINE GLOBAL INDONESIA</h3>
            <h3>VISION</h3>
            <p>To become one of the premiere companies in manning industry.</p>
            <h3>MISSION</h3>
            <p>We shall transform man to a trained and skilled individual through rigid training and instill work value for the satisfaction of customers.</p>
            <h3>OBJECTIVES</h3>
            <p>1. Enforce discipline and maintain order in the company, and<br/>2. Promote efficiency in business operations so as to achieve greater productivity in providing quality service to customers.</p>
            <h3>WORK ETHICS</h3>
            <p>1. Are expected to be courteous to customers, applicants, guests and co-employees,<br/>2. Must exercise honesty in the performance of their duties and functions,<br/>3. Must manage the funds and assets of the company honestly,<br/>4. Handle the company&apos;s equipment, materials and supplies carefully and wisely,<br/>5. Are expected to maintain high moral standards of behavior and refrain from engaging in any indecent, illegal or immoral acts that are detrimental to company&apos;s integrity and loss of confidence by clients,<br/>6. Are expected to perform their duties in the most possible efficient manner,<br/>7. Must exercise due care to conserve electricity and water, and<br/>8. Are expected to abide by the security and safety rules of the company.</p>
            <h3>RECRUITMENT AND SELECTION OF EMPLOYEES</h3>
            <p>1. Hiring of personnel is based on the approved manpower needs per department. Any additional hiring in excess of this must be properly justified, subject to the approval of the Director.<br/>2. Various positions are announced through advertisement, or notices posted on the bulletin boards and other strategic areas of the company. Employees, their friends and relatives and other contacts may recommend applicants.<br/>3. All applicant must submit their resume and curriculum vitae.<br/>4. All applicants to be hired shall have the final approval of the Director.<br/>5. Applicants must submit the following pre-employment requirements prior to actual hiring.<br/>◆Passport<br/>◆Identification card<br/>◆Medical Certificate<br/>◆2x2 photographs (2 pcs.)<br/>◆Transcript of Records, original (for verification) and photocopy<br/>◆Certification of graduation, original (for verification) and photocopy.<br/>◆Certificate of Employment, and copy of clearance from latest employer.<br/>◆Other requirements, as may be needed.<br/>6. Applicants must complete the pre-employment requirements before reporting to work.<br/>7. HRD prepares the Employment Contract /Appointment and issues an ID to the new hire. Accounting – Payroll Dept. coordinates issuance of an ATM card with the accredited bank for salary deposit and withdrawal purposes.( If required )<br/>8. The new hire undergoes an orientation with the department where he belongs during his first week of employment.<br/>9. The new employee shall be responsible for the continuing accuracy of all data related to his personal and professional information and regularly update his HRD file.</p>
            <h3>PERSONNEL FILES AND CHANGES IN PERSONAL STATUS</h3>
            <p>1. An employee&apos;s file folder contains all the paper copies and documentation about the employee which have accumulated throughout his stay with the institution.<br/>2. It is the employee&apos;s responsibility to ensure that his records are up to date and should notify in writing of any of the following changes:<br/>◆Name<br/>◆Address/residence<br/>◆Telephone number<br/>◆No. of dependents and changes in dependent status<br/>◆Change of marital status<br/>◆Persons to be notified in case of emergency<br/>◆Attendance to seminars/trainings<br/>◆Other relevant information as needed.<br/>3. Where applicable, the employee must submit supporting documents.<br/>4. The company will normally release personnel information in writing only after obtaining the written consent of the employee concerned, except release of information to cooperate with legal, safety and medical official who have a need to know specific employee information.<br/>5. Employee may review and/or copy, but not remove, the following documents in their HRD file:<br/>◆Their performance evaluation results<br/>◆Certifications<br/>◆Recommendation/referrals<br/>◆Resumes<br/>◆School credentials<br/>◆Other data as may be needed<br/>6. A resigned employee&apos;s file folder is retained only for three (3) years after which, the basic information about the employee may be obtained only through company&apos;s database. All paper copies will be disposed of after three (3) years.</p>
            <h3>EMPLOYMENT</h3>
            <p>Security of tenure<br/>In cases or regular employment, the employer shall not terminate the services of an employee for a just cause or when authorized by this Title. An employee who is unjustly dismissed from work shall be entitled to reinstatement without loss of rights and other privileges and to his full backwages, inclusive of allowances, and to his other benefits or their monetary equivalent computed from the time his compensation was withheld from him up to the time of his actual reinstatement.</p>
            <p>Regular and casual employment<br/>The provisions of written agreement to the contrary notwithstanding and regardless of the oral agreement of the parties, an employment shall be deemed to be regular where the employee has been engaged to perform activities which are usually necessary or desirable in the usual business or trade of the employer, except where the employment has been fixed for a specific project or of the employer, except where the employment has been fixed for a specific project or undertaking the completion or termination of which has been determined at the time of the engagement of the employee or where the work to be performed is seasonal in nature and the employment is for the duration of the season. An employment shall be deemed to be casual if it is not covered by the preceding paragraph: Provided, That any employee who has rendered at least one year of service, whether such service is continuous or broken, shall be considered a regular employee with respect to the activity in which he is employed and his employment shall continue while such activity exists.</p>
            <p>Probationary employment<br/>Probationary employment shall not exceed six (6) months from the date the employee started working, unless it is covered by an apprenticeship agreement stipulating a longer period. The services of an employee who has been engaged on a probationary period may be terminated for a just cause or when he/she fails to qualify for a regular employee in accordance with reasonable standards made known by the employer to the employee at the time of his/her engagement. An employee who is allowed to work after a probationary period shall be considered a regular employee.</p>
            <p>Termination by employer<br/>An employer may terminate an employment for any of the following causes:<br/>(a) Serious misconduct or willful disobedience by the employee of the lawful orders of his employer or representative in connection with his work;<br/>(b) Gross and habitual neglect by the employee of his duties.<br/>(c) Involvement in a bribery and corruption.<br/>(d) Embezzlement of company funds.<br/>(e) Fraud or willful breach by the employee of the trust reposed in her/him by her/his employer or duly authorized representative;<br/>(f) Commission of a crime or offense by the employee against the person of her/his employer or any immediate member of her/his family or her/his duly authorized representatives and;<br/>(g) Other causes analogous to the foregoing.<br/>(h) Wilful leakage of the company&apos;s confidential information.</p>
            <h3>HOURS OF WORK</h3>
            <p>The provisions of this rule shall apply to all employees including managerial employees such as QMR and Director.</p>
            <p>ATTENDANCE AND TIME KEEPING<br/>1. The company adopts 7.5hours of work per day forweek days and 3.5hours for Saturday.<br/>2. Working time is from 0830 to 1700 for week days, from 0830 to 1200 for Saturday,and Sundayis no working holidays, however, in the event of an emergency case or a case required by the QMR all the staffs shall be attended to the office any time regardless week end and holidays.<br/>3. Attendance of all employees is recorded through a log book. The employee must record personally time in/out with honesty.<br/>4. Failure to time in and out is a presumption of absence from work.<br/>5. Three (3) consecutive days of tardiness in a week is a presumption of absence.<br/>6. Proxy time is strictly prohibited.</p>
            <p>UNDERTIME<br/>1. Undertime means leaving one&apos;s workplace before the end of one&apos;s official time. An employee who needs to go undertime for any valid reason must first secure permission from the QMR.<br/>2. Undertimealso means time spending for a private affair, during official working hours.<br/>3. No employeesare allowed to leave the premises without securing approval as such.<br/>4. No employees are allowed to spend undertime.</p>
            <p>ABSENCES<br/>1. The QMR must be informed as soon as possible by all means of communications prior to the start of the work day in case an employee is unable to report for work for any reason. If the Department Head cannot be reached the employee should notify any of her/his co-employees to relay the message to the Department Head.<br/>2. Application for leave must be accomplished before or immediately after the absence.<br/>3. Absence refers to an employees&apos; failure to report to work. Absence without prior approval is considered as AWOL (&quot;Absence Without Leave&quot;)<br/>4. An employee is considered on AWOL status if her/his immediate superior/coordinator is not immediately notified of her/his whereabouts after incurring the absence.<br/>5. An employee is considered on AWOL status if the absence incurred is more than one day without leave application.<br/>6. An employee who is AWOL for 3 consecutive days is automatically considered dismissed.<br/>7. Except for emergency/sick leaves, absences with or without pay must be filed in advance.<br/>8. An employee who is absent on ground of illness must accomplish a sick leave application form accompanied by a medical certificate.<br/>9. Natural disasters of a force majeure recognized by official report will be deemed as an emergency and it will automatically means suspension of work.<br/>10. Absences incurred in excess of allowed leave incentives will be charged to regular wage.</p>
            <p>SICK LEAVE<br/>Understanding the Sick Leave Policy<br/>Although technically called &quot;sick&quot; leaves and used supposedly only when an employee is sick, some times will require getting advance leave approval for a non-emergency sick leave, such as a visit to a doctor. For sudden occurrences, such as a sudden onset of fever, a standard policy on sick leave would be to inform the QMR at least two hours before the shift. Failing to call may invalidate the sick leave and consider it unauthorized.<br/>Sick leaves may be used for medical, dental, or optical appointment, and in the following cases and so on ;<br/> Suffering from a sickness or injury;<br/> Maternal reasons;<br/> To care for a sick or injured member of the family;<br/> If reporting to work can jeopardize own health and that of colleagues;<br/> Death of a member of immediate family</p>
            <p>EMERGENCY LEAVE<br/>1. The QMR must be informed as soon as possible or within 24 hours by all means of communications in case of emergency leave. If the QMR cannot be reached the employee should notify any of his co-employees to relay the message to the QMR.<br/>2. An emergency leave is good for one (1) day only. The QMR must be informed as soon as possible or within 24 hours by all means of communications in case of extended emergency leave.<br/>3. The employee must immediately file a formal leave upon resumption to work.</p>
            <p>BEREAVEMENT LEAVE<br/>1. Regular employees are entitled to a bereavement leave of three (3) days with pay over and above their vacation leave credits. The employee may avail if this benefit within a maximum of three (3) days during and after the death of the family member.<br/>2. The three (3) days must be continuous and inclusive. It cannot be availed on a staggered basis.<br/>3. The immediate relative means: father, mother and sibling for unmarried and spouse and children for married.<br/>4. The Application Form must be filed immediately upon learning of the family member&apos;s death or immediately upon reporting to work after the burial.<br/>5. The bereavement leave is considered a legitimate leave with pay for the number of leaves given to an employee and therefore, no deduction is made from the employee&apos;s monthly salary when availing of this leave.</p>
            <p>RETURN TO WORK CERTIFICATION<br/>1. Employees who are on sick leave or an extended sick leave must submit a doctor&apos;s medical report to the QMR, once return to work.<br/>2. Employees who are on bereavement leave must submit a certificate in order to prove death of immediate relative.</p>
            <h3>HOLIDAYS</h3>
            <p>1. Government designated holidays.<br/>TANGGAL HARI KETERANGAN<br/>1 01 Januari Rabu YearBaru 2014<br/>2 14 Januari Selasa MaulidNabi Muhammad SAW<br/>3 31 Januari Jumat YearBaruImlek 2565 Kongzili<br/>4 31 Maret Senin Hari Raya NyepiYearBaruSaka 1936<br/>5 18 April Jumat Wafat Isa Almasih<br/>6 01 Mei Kamis MemperingatiHariBuruhInternasional<br/>7 15 Mei Kamis Hari Raya Waisak 2558<br/>8 27 Mei Selasa IsraMikrajNabi Muhammad SAW<br/>9 29 Mei Kamis Kenaikan Isa Almasih<br/>10 28 Juli Senin-Selasa ( Lebaran ) Hari Raya IdulFitri 1435 Hijriyah<br/>11 29 Juli<br/>12 30 Juli Rabu, Kamis Dan Jumat Hari Raya Idulfitri 1435 Hijriyah<br/>13 31 Juli<br/>14 01 Augustus<br/>15 17 Agustus Minggu HariKemerdekaan RI<br/>16 05 Oktober Minggu Hari Raya IdulAdha 1435 Hijriyah<br/>17 25 Oktober Sabtu YearBaru 1436 Hijriyah<br/>18 25 Desember Kamis Hari Raya Natal<br/>19 26 Desember Jumat Hari Raya Natal</p>
            <p>2. Though the days of &quot;Rabu, Kamis Dan Jumat&quot;( three days ) are designated by the government as the holidays consecutively from the &quot;Lebaran&quot;, half of skeleton staffsshould be attended to the office for first two days, however, HGI set up the third dayof &quot;Rabu, Kamis Dan Jumat&quot; as a normal working day. The QMR is responsible to assign those staffs who shall attend to the office for &quot;Rabu, Kamis Dan Jumat&quot;.<br/>3. For any national/religious holidays other than the week end, one duty officer shall be attended to the office for monitoring if any important information from the principals or the vessel masters. The QMR has to assign the duty officers for those holidays. Of course, any important information from the principal or the vessel masters should be reported to the QMR, immediately.</p>
            <h3>PERSONAL APPEARANCE AND DRESS CODE</h3>
            <p>1. All employees are representatives of the company and are expected to dress professionally and presentably while inside and outside the company premises.<br/>2. Employees must follow the dress code during work hours.<br/>3. Staffs may wear civilian clothes while performing overtime work during weekends.<br/>4. Female employees are not allowed to wear collarless t-shirts, sleeveless shirts, denim jeans, and slippers while at work during regular working days.<br/>5. Male employees are not allowed to wear collarless t-shorts, sleeveless shirts, denim jeans, and slippers while at work during regular working days.<br/>6. Male employees must be clean-shaven. Haircut must not touch the collar of the shirt. Wearing of earrings is not allowed for male employees.<br/>7. Employees attending seminars/conferences have to neat wear or suit.<br/>8. The prescribed neat wear includes the following:<br/>a.) Female Employees<br/> Closed shoes (Slippers or sandals are not allowed)<br/> Employee I.D.<br/>b.) Male Employees<br/> Black/dark leather shoes with socks (Slippers or sandals are not allowed)<br/> Employee I.D.<br/>9. Pregnant female employees are allowed to wear at their comfort.<br/>10. It is expected that all employees are exempted for wearing good judgment and meet acceptable norms for personal cleanliness, hygiene and grooming.</p>
            <h3>EMPLOYEE ID</h3>
            <p>1. All employees are required to wear their ID at all times while at work and while inside the premises of the company.<br/>2. The employee must wear her/his ID immediately upon entering the building for proper identification by the guard.<br/>3. An employee whose ID is lost or misplaced should report within three (3) working days.<br/>4. The employee ID is non-transferable and is the property of the company. It should be returned upon termination of employment.</p>
            <h3>PROPOSED DECORUM INSIDE THE OFFICES AND OTHER WORK AREAS</h3>
            <p>1. Heads, Managers must ensure that only authorized personnel are allowed entry in the different departments/work areas of the company.<br/>2. Eating, loitering, chatting, using a radio headset/earphones, extended use of telephones at work and other activities not related to work are not allowed.<br/>3. Other activities not related to work may be allowed during break time.<br/>4. Telephone calls must be answered promptly in the most courteous and professional manner.<br/>5. All employees must handle confidential information with integrity and responsibly.<br/>6. It is the responsibility of the employees to immediately report any hazardous or unsafe condition/s on building for prompt action.<br/>7. Employees are not allowed to sell/nor collect payments, and accept &quot;gift&quot; from applicants/seafarers or members of their family.<br/>8. Employees are strictly prohibited in engaging in any form of activity or business transaction which is on conflict with the interest of the Agency.</p>
            <h3>TELEPHONE ETIQUETTE</h3>
            <p>1. An employee must promptly answer the phone after two rings. Do not wait for several rings before answering the call.<br/>2. Always start with a friendly greeting as follows:<br/>HGI, good morning (good afternoon/good evening or &quot;name of department&quot;, good morning (good afternoon/good evening), may I help you?<br/>3. Always speak in a courteous manner even if the person on the other line is not.<br/>4. If the person called is not around nor available, ask the caller to leave a message and inform the person called as soon as he/she is back.<br/>Recommended: &quot;He&apos;s/She&apos;s not available at the moment – may I get her/him to call you back?&quot; – would you like to leave a message?<br/>5. Always have a pen and paper ready to take the message.<br/>6. Do not argue with the caller nor use improper vulgar or abusive language.<br/>7. When the person called is in the same room as yours, and you answered a call for him, do not raise your voice when you ask him to take the call.<br/>8. When the person called does not belong to your department, politely apologize and transfer the call to the department concerned.<br/>9. Refrain from neither using the phone for personal calls nor engaging in lengthy personal conversations with a co-employee.<br/>10. Be patient and tolerant on difficult callers.<br/>11. Always end the call in courteous manner.</p>
            <h3>EMPLOYEE DISCIPLINE</h3>
            <p>Discipline means adherence to regulations both public and private. The complainants include company&apos;s employees., marine officers and crew managed by the company.<br/>1. Regardless of the gravity of offense, the complainant should file a written complain to the QMR. The QMR must ensure that the complainant is given due attention and must conduct an initial investigation.<br/>2. The QMR must send to the employee concerned a directive to submit a written explanation of his side within 24 to 48 hours.<br/>3. An inquiry from witness/persons involved will be conducted.<br/>4. The Department Head should settle the conflict first within the department.<br/>5. If unsettled within the department, the fact of the incident will be discussed between the Director and QMR for final decision.<br/>6. If the employees presence in the workplace poses a threat to the lives or safety of other employees or to the properties/services of the employer, then the employee is placed on preventive suspension for maximum of thirty (30) days until full investigation of the case is done and a decision is made on the disciplinary action to be given to the employee.<br/>7. The company reserves the right to withhold release of documents such as certificate of employment and the monthly salary for the employee if the employee has any pending financial obligations, unresolved administrative or legal case with the company or with any of its official.</p>
            <h3>SEXUAL HARRASMENT</h3>
            <p>1. The victim of sexual harassment may be a male or female.<br/>2. The sexual favor is made as a condition in the hiring or in the employment, re-employment or continued employment of said individual, or in granting said individual favorable compensation, terms, conditions, promotions, or privileges; or the refusal to grant the sexual favor results in limiting, segregating or classifying the employee which in any way would discriminate, deprive or diminish employment opportunities or otherwise adversely affect said employee.<br/>3. The above acts would impair the employee&apos;s rights or privileges under existing labor laws; or<br/>4. The above acts would result in an intimidating hostile, or offensive environment for the employee.<br/>5. Sexual harassment is committed by an employer, employee, manager, supervisor, agent of the employer, teacher, instructor, professor, coach, trainer, or any other person who, having authority, influence or moral ascendancy over another in a work or training or education environment, demands, requests or otherwise requires any sexual favor from the other, regardless of whether the demand, request or requirement for submission is accepted by the object of the act.</p>
            <h3>PROMOTION AND TRANSFER</h3>
            <p>1. An employee may be promoted upon the recommendation of the superior as approved by the Director.<br/>2. Promoted employees are entitled to a salary adjustment after their promotion. However, an employee who transfers to a position of the same level is not entitled to a salary adjustment.</p>
            <h3>BUSINESS GIFTS</h3>
            <p>1. Hiring will be based on established qualification and standards.<br/>2. Employees are not allowed to accept any kind of gifts, cash or reception from applicants/seafarers or members of their family inside and outside the office.<br/>3. Employees should not go out on &quot;dates&quot; with applicant/seafarers or members of their family.</p>
            <h3>POST EMPLOYMENT PROCEDURES</h3>
            <p>RESIGNATION<br/>1. An employee who is considering leaving HGI for any reason is encouraged to discuss this situation in advance with his immediate superior before making a final decision.<br/>2. Except for Managers and Heads, resignation must be submitted at least thirty (30) days prior to its effectivity in order to allow proper turnover and lead time to get a replacement. It must be noted and accepted by the employee&apos;s Head.<br/>3. Resignations are addressed to the Head concerned. Resignations must always be formally written and received by the superior concerned.</p>
            <p>RETIREMENT<br/>Retirement may be optional, mandatory and forced.<br/>1. Mandatory Retirement is at the age of 60.<br/>2. Forced Retirement is other than the above categories but is considered valid according to law.<br/>3. An employee who is planning to retire is encouraged to discuss their plans with their Head in advance of their planned retirement date.<br/>4. A retiring employee should submit a written letter addressed to the Director regarding his/her retirement date. The Director forwards said letter to Accounting Payroll for processing.<br/>5. The retiring employee obtains an Exit Clearance/Quitclaim Form and secures its completion.</p>
            <p>EMPLOYEE TERMINATION/DISMISSAL<br/>1. The company may terminate the services of an employee of the following just causes:<br/>a) Serious misconduct or willful disobedience by the employee of the lawful orders of his/her employer or employer representative in connection with his/her work.<br/>b) Involvement in a bribery and corruption.<br/>c) Embezzlement of company funds.<br/>d) Gross and habitual neglect by the employee of his duties.<br/>e) Fraud or willful breach by the employee of the trust reposed in her/him by her/his employer or duly authorized representative.<br/>f) Commission of a crime or offense by the employee against the person of her/his employer or any immediate member of her/his family or her/his duly authorized representatives and;<br/>g) Other causes analogous to the foregoing.<br/>2. Closure of the establishment and reduction of personnel due to the installation of labor-saving devices, redundancy, and retrenchment to prevent losses or the closing or cessation of operation of the establishment, may serve as just causes for employee termination.<br/>3. An employer may terminate the services of an employee who has been found to be suffering from any disease and whose continued employment is prohibited by law or is prejudicial to his/her health as well as of his/her co-employees.<br/>4. The employee may terminate the employee-employer relationship without serving any notice to the employer for any of the following just causes:<br/>a) Serious insult by the employer or by his/her representative on the honor and person of the employee.<br/>b) Inhuman and unbearable treatment accorded the employee by the employer or his/her representative;<br/>c) Commission of a crime or offense by the employer or his/her representative against the person of the employee or any of the immediate members of his/her family; and<br/>d) Other causes analogous to any of the foregoing.<br/>5. Due process shall be given to any employee who is being recommended for termination/dismissal for just cause.</p>
            <h3>CODE OF DISCIPLINE</h3>
            <p>TABLE OF OFFENSES AND PENALTIES</p>
            <table className="border-collapse border border-gray-400">
              <thead>
                <tr>
                  <th className="border border-gray-400 p-2">Offense</th>
                  <th className="border border-gray-400 p-2">1st Offense</th>
                  <th className="border border-gray-400 p-2">2nd Offense</th>
                  <th className="border border-gray-400 p-2">3rd Offense</th>
                </tr>
              </thead>
              <tbody>
                <tr><td className="border border-gray-400 p-2">1. Falsification of forgery of company records/documents</td><td className="border border-gray-400 p-2">30 days suspension to dismissal depending upon the gravity of offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">2.Absence without official leave (AWOL) from one (1) to six (6) consecutive days</td><td className="border border-gray-400 p-2">Warning to 7 days suspension</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td></tr>
                <tr><td className="border border-gray-400 p-2">3.Absence without official leave (AWOL) for seven (7) consecutive days or more</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">4.Dishonesty, fraud, or willful breach of trust in the conduct of one&apos;s job.</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense.</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">5.Giving false testimony during an investigation.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">6.planting evidence against another employee for the purpose of unduly imputing a crime</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">7.Coercion or intimidation which adversely affects the welfare of the company&apos;s interest, reputation or goodwill.</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">8.Demanding or accepting directly or indirectly money, or anything of value, or any other thereof, from applicants or co-employees as a condition for the performance of one&apos;s duty or any other activity.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">9.Fighting or provoking a fight, inciting disorders or any display of violence within company premises.</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">10.Using or possessing prohibited drugs within or outside the company premises.</td><td className="border border-gray-400 p-2">30 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">11.Unathorized solicitation or collecting contribution money from crew, clients, guests, employees of the company for any purpose whatsoever</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">12.Insult, discourtesy, rudeness to any company officer, co-employees, and crew or company guests.</td><td className="border border-gray-400 p-2">Stern warning to dismissal depending upon the gravity of the offense.</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">13.Concealment of a communicable disease and or debilitating disease which endangers the health of co-employees.</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">14.Reporting for work under the influence of intoxicating beverages.</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">15.Scandolous or malicious acts and lewd or indecent behavior or exposure within company premises.</td><td className="border border-gray-400 p-2">15 days dismissal</td><td className="border border-gray-400 p-2">30 days suspension</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">16.Spreading false rumors or gossip about the company, co-employees, crews, clients or third parties doing business with the company.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">3 days suspension</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">17.Exercising any act of authority under false pretenses.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">18.Malingering or pretending to be ill to escape work.</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">19.Negligence in the performance of work.</td><td className="border border-gray-400 p-2">Stern warning to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">20.Charging personal long distance calls to the company without prior permission.</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">30 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td></tr>
                <tr><td className="border border-gray-400 p-2">21.Unofficial selling, solicitation or collection of contributions for any purpose whatsoever.</td><td className="border border-gray-400 p-2">Stern warning</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td></tr>
                <tr><td className="border border-gray-400 p-2">22.Unathorized use of the company&apos;s name for personal gain.</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">23.Providing company information to any business, service or activity that is in competition with the company prior authorization.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">24.Direct refusal, willful failure or delay to accomplish an assigned task. Refusing to accept or carry out official assignments, duty or specific instructions given by superior (insubordination)</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">25.Disrepsect to superiors; threats or intimidation against company authorities.</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">26.Using company equipment and facilities for personal reasons</td><td className="border border-gray-400 p-2">Stern warning</td><td className="border border-gray-400 p-2">7 days suspension</td><td className="border border-gray-400 p-2">15 days suspension</td></tr>
                <tr><td className="border border-gray-400 p-2">27. Holding unofficial or unauthorized meetings within the company&apos;s premises</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">30 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td></tr>
                <tr><td className="border border-gray-400 p-2">28. Furnishing of incorrect or misleading data to employees or persons.</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">29. Losing, misplacing, destruction or damage to company&apos;s records</td><td className="border border-gray-400 p-2">Suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">30. Misappropriation of the company&apos;s funds and properties.</td><td className="border border-gray-400 p-2">Stern warning to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">31. Failure to liquidate or render an accounting of expenses charged to the company</td><td className="border border-gray-400 p-2">Stern warning to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">32. Stealing or pilferage or attempting to steal or pilfer from the company or its clients.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">33. Knowingly giving false or misleading information in applications for employment.</td><td className="border border-gray-400 p-2">15 days suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">34. Vandalism of any form, acts f sabotage, intentional destruction of company&apos;s property.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">35. Engaging directly or indirectly with another business or enterprise for personal reasons in behalf of the company.</td><td className="border border-gray-400 p-2">15 days suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">36. Disclosing sensitive information relating to the company&apos;s business/es or operations</td><td className="border border-gray-400 p-2">15 days suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">37. Handling or use of company&apos;s property without prior authorization</td><td className="border border-gray-400 p-2">Stern warning</td><td className="border border-gray-400 p-2">7 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td></tr>
                <tr><td className="border border-gray-400 p-2">38. Deliberate destruction or damage to company records</td><td className="border border-gray-400 p-2">Stern warning to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">39. Allowing oneself to be relieved by another known to be under the influence of liquor or narcotics</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">40. Unauthorized possession of explosives, dangerous chemical or other deadly weapons within the company premises.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">41. Assaults or attempts to do harm on another within the company premises.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">42. Deliberate misuse or removal from the company premises any records without proper authority.</td><td className="border border-gray-400 p-2">15 days suspension</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">43. Publishing or disseminating false or malicious statements concerning employees and officers of the company.</td><td className="border border-gray-400 p-2">Dismissal</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">44. Public display of affection.</td><td className="border border-gray-400 p-2">7 days suspension</td><td className="border border-gray-400 p-2">15 days of suspension</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">45. Sexual harassment including cadets, crew and applicants.</td><td className="border border-gray-400 p-2">suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">46. Reproduction of handouts/manuals, exams and any other printed material for personal reason without prior approval from the management.</td><td className="border border-gray-400 p-2">15 days suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
                <tr><td className="border border-gray-400 p-2">47. Immorality</td><td className="border border-gray-400 p-2">suspension to dismissal depending upon the gravity of the offense</td><td className="border border-gray-400 p-2">-</td><td className="border border-gray-400 p-2">-</td></tr>
              </tbody>
            </table>
            <p><em>Note: This is a comprehensive summary of the Management Guidelines for Office Employees. The full document contains detailed policies and procedures for employee conduct, discipline, and company operations.</em></p>
          </div>
        </div>
      </main>
    </div>
  );
}